
    create table trade.strategies (
        exclusive_orders boolean not null,
        hedge_mode boolean not null,
        leverage float4 not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        description varchar(255),
        exchange varchar(255),
        name varchar(255),
        symbol varchar(255),
        timeframe varchar(255),
        primary key (id)
    );

    create table exchange_api_keys (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        user_id bigint not null,
        api_key varchar(255) not null,
        exchange varchar(255) not null check (exchange in ('BINANCE','COINBASE','KRAKEN','BYBIT','SIMULATED','UNKNOWN')),
        secret_key varchar(255) not null,
        primary key (id)
    );

    create table order_items (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        order_id bigint not null,
        strategy_item_id bigint not null unique,
        updated_at timestamp(6) not null,
        primary key (id)
    );

    create table orders (
        canceled_at timestamp(6),
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        total_price bigint not null,
        updated_at timestamp(6) not null,
        status varchar(255) not null check (status in ('DONE','CANCELED')),
        primary key (id)
    );

    create table payment_txns (
        amount numeric(38,2) not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        point_txn_id bigint not null unique,
        updated_at timestamp(6) not null,
        user_id bigint not null,
        payment_key varchar(255) not null,
        status varchar(255) not null check (status in ('DONE','CANCELED')),
        primary key (id)
    );

    create table point_txns (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        point bigint not null,
        updated_at timestamp(6) not null,
        user_id bigint not null,
        status varchar(255) not null check (status in ('CHARGE','USE')),
        primary key (id)
    );

    create table strategy_items (
        id bigint generated by default as identity,
        price bigint not null,
        strategy_id bigint not null unique,
        description varchar(255) not null,
        name varchar(255) not null,
        primary key (id)
    );

    create table user_strategy_items (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        strategy_item_id bigint not null unique,
        updated_at timestamp(6) not null,
        user_id bigint not null unique,
        primary key (id)
    );

    create table users (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        point bigint not null check (point >= 0),
        updated_at timestamp(6) not null,
        email varchar(255),
        nickname varchar(255) not null,
        oauth_id varchar(255) not null,
        oauth_provider varchar(255) not null check (oauth_provider in ('KAKAO','GOOGLE')),
        refresh_token varchar(255),
        primary key (id)
    );

    alter table if exists exchange_api_keys 
       add constraint exchange_api_keys_user_id_fk 
       foreign key (user_id) 
       references users;

    alter table if exists order_items 
       add constraint order_items_order_id_fk 
       foreign key (order_id) 
       references orders;

    alter table if exists order_items 
       add constraint order_items_strategy_item_id_fk 
       foreign key (strategy_item_id) 
       references strategy_items;

    alter table if exists payment_txns 
       add constraint payment_txns_point_txn_id_fk 
       foreign key (point_txn_id) 
       references point_txns;

    alter table if exists payment_txns 
       add constraint payment_txns_user_id_fk 
       foreign key (user_id) 
       references users;

    alter table if exists point_txns 
       add constraint point_txns_user_id_fk 
       foreign key (user_id) 
       references users;

    alter table if exists strategy_items 
       add constraint strategy_items_strategy_id_fk 
       foreign key (strategy_id) 
       references trade.strategies;

    alter table if exists user_strategy_items 
       add constraint user_strategies_strategy_item_id_fk 
       foreign key (strategy_item_id) 
       references strategy_items;

    alter table if exists user_strategy_items 
       add constraint user_strategies_user_id_fk 
       foreign key (user_id) 
       references users;

    create table trade.strategies (
        exclusive_orders boolean not null,
        hedge_mode boolean not null,
        leverage float4 not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        description varchar(255),
        exchange varchar(255),
        name varchar(255),
        symbol varchar(255),
        timeframe varchar(255),
        primary key (id)
    );

    create table exchange_api_keys (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        user_id bigint not null,
        api_key varchar(255) not null,
        exchange varchar(255) not null check (exchange in ('BINANCE','COINBASE','KRAKEN','BYBIT','SIMULATED','UNKNOWN')),
        secret_key varchar(255) not null,
        primary key (id)
    );

    create table order_items (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        order_id bigint not null,
        strategy_item_id bigint not null unique,
        updated_at timestamp(6) not null,
        primary key (id)
    );

    create table orders (
        canceled_at timestamp(6),
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        total_price bigint not null,
        updated_at timestamp(6) not null,
        status varchar(255) not null check (status in ('DONE','CANCELED')),
        primary key (id)
    );

    create table payment_txns (
        amount numeric(38,2) not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        point_txn_id bigint not null unique,
        updated_at timestamp(6) not null,
        user_id bigint not null,
        payment_key varchar(255) not null,
        status varchar(255) not null check (status in ('DONE','CANCELED')),
        primary key (id)
    );

    create table point_txns (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        point bigint not null,
        updated_at timestamp(6) not null,
        user_id bigint not null,
        status varchar(255) not null check (status in ('CHARGE','USE')),
        primary key (id)
    );

    create table strategy_items (
        id bigint generated by default as identity,
        price bigint not null,
        strategy_id bigint not null unique,
        description varchar(255) not null,
        name varchar(255) not null,
        primary key (id)
    );

    create table user_strategy_items (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        strategy_item_id bigint not null unique,
        updated_at timestamp(6) not null,
        user_id bigint not null unique,
        primary key (id)
    );

    create table users (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        point bigint not null check (point >= 0),
        updated_at timestamp(6) not null,
        email varchar(255),
        nickname varchar(255) not null,
        oauth_id varchar(255) not null,
        oauth_provider varchar(255) not null check (oauth_provider in ('KAKAO','GOOGLE')),
        refresh_token varchar(255),
        primary key (id)
    );

    alter table if exists exchange_api_keys 
       add constraint exchange_api_keys_user_id_fk 
       foreign key (user_id) 
       references users;

    alter table if exists order_items 
       add constraint order_items_order_id_fk 
       foreign key (order_id) 
       references orders;

    alter table if exists order_items 
       add constraint order_items_strategy_item_id_fk 
       foreign key (strategy_item_id) 
       references strategy_items;

    alter table if exists payment_txns 
       add constraint payment_txns_point_txn_id_fk 
       foreign key (point_txn_id) 
       references point_txns;

    alter table if exists payment_txns 
       add constraint payment_txns_user_id_fk 
       foreign key (user_id) 
       references users;

    alter table if exists point_txns 
       add constraint point_txns_user_id_fk 
       foreign key (user_id) 
       references users;

    alter table if exists strategy_items 
       add constraint strategy_items_strategy_id_fk 
       foreign key (strategy_id) 
       references trade.strategies;

    alter table if exists user_strategy_items 
       add constraint user_strategies_strategy_item_id_fk 
       foreign key (strategy_item_id) 
       references strategy_items;

    alter table if exists user_strategy_items 
       add constraint user_strategies_user_id_fk 
       foreign key (user_id) 
       references users;
