
    create table exchange_api_keys (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        user_id bigint not null,
        api_key varchar(255) not null,
        exchange_type varchar(255) not null check (exchange_type in ('BINANCE','COINBASE','KRAKEN','BYBIT','SIMULATED','UNKNOWN')),
        secret_key varchar(255) not null,
        primary key (id)
    );

    create table payment_txns (
        amount numeric(38,2) not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        point_txn_id bigint not null unique,
        updated_at timestamp(6) not null,
        user_id bigint not null,
        payment_key varchar(255) not null,
        status varchar(255) not null check (status in ('DONE','CANCELED')),
        primary key (id)
    );

    create table point_txns (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        point bigint not null,
        updated_at timestamp(6) not null,
        user_id bigint not null,
        status varchar(255) not null check (status in ('CHARGE','USE')),
        primary key (id)
    );

    create table strategies (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        price bigint not null,
        updated_at timestamp(6) not null,
        description varchar(255) not null,
        name varchar(255) not null,
        path varchar(255) not null,
        primary key (id)
    );

    create table user_strategies (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        strategy_id bigint not null unique,
        updated_at timestamp(6) not null,
        user_id bigint not null unique,
        primary key (id)
    );

    create table users (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        point bigint not null check (point >= 0),
        updated_at timestamp(6) not null,
        email varchar(255),
        nickname varchar(255) not null,
        oauth_id varchar(255) not null,
        oauth_provider varchar(255) not null check (oauth_provider in ('KAKAO','GOOGLE')),
        refresh_token varchar(255),
        primary key (id)
    );

    alter table if exists exchange_api_keys 
       add constraint FKla32n58cpelb0t78gkrtvdv33 
       foreign key (user_id) 
       references users;

    alter table if exists payment_txns 
       add constraint payment_txns_point_txn_id_fk 
       foreign key (point_txn_id) 
       references point_txns;

    alter table if exists payment_txns 
       add constraint payment_txns_user_id_fk 
       foreign key (user_id) 
       references users;

    alter table if exists point_txns 
       add constraint point_txns_user_id_fk 
       foreign key (user_id) 
       references users;

    alter table if exists user_strategies 
       add constraint user_strategies_strategy_id_fk 
       foreign key (strategy_id) 
       references strategies;

    alter table if exists user_strategies 
       add constraint user_strategies_user_id_fk 
       foreign key (user_id) 
       references users;
